# Website settings
title: Arrowtooth Flounder assessment
author:
  name: Chris Grandin
  email: chris.grandin@gmail.com
decription: "Arrowtooth assessment content including links to documents and slides for presentations."

# Build seettings
remote_theme: jekyll/minima
exclude:
  - csas-review/assessment-main.Rmd
  - pre-review-responses/responses-to-twg.rmd
  - errata/note-to-participants-pre-review.Rmd
